// Generated by gencpp from file asr_usercommand/usercommand.msg
// DO NOT EDIT!


#ifndef ASR_USERCOMMAND_MESSAGE_USERCOMMAND_H
#define ASR_USERCOMMAND_MESSAGE_USERCOMMAND_H

#include <ros/service_traits.h>


#include <asr_usercommand/usercommandRequest.h>
#include <asr_usercommand/usercommandResponse.h>


namespace asr_usercommand
{

struct usercommand
{

typedef usercommandRequest Request;
typedef usercommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct usercommand
} // namespace asr_usercommand


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::asr_usercommand::usercommand > {
  static const char* value()
  {
    return "71ac060476c0905d0416477df3715d0f";
  }

  static const char* value(const ::asr_usercommand::usercommand&) { return value(); }
};

template<>
struct DataType< ::asr_usercommand::usercommand > {
  static const char* value()
  {
    return "asr_usercommand/usercommand";
  }

  static const char* value(const ::asr_usercommand::usercommand&) { return value(); }
};


// service_traits::MD5Sum< ::asr_usercommand::usercommandRequest> should match 
// service_traits::MD5Sum< ::asr_usercommand::usercommand > 
template<>
struct MD5Sum< ::asr_usercommand::usercommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::asr_usercommand::usercommand >::value();
  }
  static const char* value(const ::asr_usercommand::usercommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::asr_usercommand::usercommandRequest> should match 
// service_traits::DataType< ::asr_usercommand::usercommand > 
template<>
struct DataType< ::asr_usercommand::usercommandRequest>
{
  static const char* value()
  {
    return DataType< ::asr_usercommand::usercommand >::value();
  }
  static const char* value(const ::asr_usercommand::usercommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::asr_usercommand::usercommandResponse> should match 
// service_traits::MD5Sum< ::asr_usercommand::usercommand > 
template<>
struct MD5Sum< ::asr_usercommand::usercommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::asr_usercommand::usercommand >::value();
  }
  static const char* value(const ::asr_usercommand::usercommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::asr_usercommand::usercommandResponse> should match 
// service_traits::DataType< ::asr_usercommand::usercommand > 
template<>
struct DataType< ::asr_usercommand::usercommandResponse>
{
  static const char* value()
  {
    return DataType< ::asr_usercommand::usercommand >::value();
  }
  static const char* value(const ::asr_usercommand::usercommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASR_USERCOMMAND_MESSAGE_USERCOMMAND_H
