// Generated by gencpp from file facedetect/FacePositionRequest.msg
// DO NOT EDIT!


#ifndef FACEDETECT_MESSAGE_FACEPOSITIONREQUEST_H
#define FACEDETECT_MESSAGE_FACEPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace facedetect
{
template <class ContainerAllocator>
struct FacePositionRequest_
{
  typedef FacePositionRequest_<ContainerAllocator> Type;

  FacePositionRequest_()
    : trigger(0)  {
    }
  FacePositionRequest_(const ContainerAllocator& _alloc)
    : trigger(0)  {
    }



   typedef int32_t _trigger_type;
  _trigger_type trigger;




  typedef boost::shared_ptr< ::facedetect::FacePositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::facedetect::FacePositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FacePositionRequest_

typedef ::facedetect::FacePositionRequest_<std::allocator<void> > FacePositionRequest;

typedef boost::shared_ptr< ::facedetect::FacePositionRequest > FacePositionRequestPtr;
typedef boost::shared_ptr< ::facedetect::FacePositionRequest const> FacePositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::facedetect::FacePositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::facedetect::FacePositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace facedetect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::facedetect::FacePositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::facedetect::FacePositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::facedetect::FacePositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::facedetect::FacePositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::facedetect::FacePositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::facedetect::FacePositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::facedetect::FacePositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0373c780359f7744644a5cb91600d83";
  }

  static const char* value(const ::facedetect::FacePositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0373c780359f774ULL;
  static const uint64_t static_value2 = 0x4644a5cb91600d83ULL;
};

template<class ContainerAllocator>
struct DataType< ::facedetect::FacePositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "facedetect/FacePositionRequest";
  }

  static const char* value(const ::facedetect::FacePositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::facedetect::FacePositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 trigger\n\
";
  }

  static const char* value(const ::facedetect::FacePositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::facedetect::FacePositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trigger);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct FacePositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::facedetect::FacePositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::facedetect::FacePositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "trigger: ";
    Printer<int32_t>::stream(s, indent + "  ", v.trigger);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACEDETECT_MESSAGE_FACEPOSITIONREQUEST_H
