// Generated by gencpp from file facedetect/FacePositionResponse.msg
// DO NOT EDIT!


#ifndef FACEDETECT_MESSAGE_FACEPOSITIONRESPONSE_H
#define FACEDETECT_MESSAGE_FACEPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace facedetect
{
template <class ContainerAllocator>
struct FacePositionResponse_
{
  typedef FacePositionResponse_<ContainerAllocator> Type;

  FacePositionResponse_()
    : x(0.0)
    , y(0.0)  {
    }
  FacePositionResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::facedetect::FacePositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::facedetect::FacePositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FacePositionResponse_

typedef ::facedetect::FacePositionResponse_<std::allocator<void> > FacePositionResponse;

typedef boost::shared_ptr< ::facedetect::FacePositionResponse > FacePositionResponsePtr;
typedef boost::shared_ptr< ::facedetect::FacePositionResponse const> FacePositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::facedetect::FacePositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::facedetect::FacePositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace facedetect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::facedetect::FacePositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::facedetect::FacePositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::facedetect::FacePositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::facedetect::FacePositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::facedetect::FacePositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::facedetect::FacePositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::facedetect::FacePositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::facedetect::FacePositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::facedetect::FacePositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "facedetect/FacePositionResponse";
  }

  static const char* value(const ::facedetect::FacePositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::facedetect::FacePositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
\n\
\n\
";
  }

  static const char* value(const ::facedetect::FacePositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::facedetect::FacePositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct FacePositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::facedetect::FacePositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::facedetect::FacePositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACEDETECT_MESSAGE_FACEPOSITIONRESPONSE_H
