// Generated by gencpp from file facedetect/FacePosition.msg
// DO NOT EDIT!


#ifndef FACEDETECT_MESSAGE_FACEPOSITION_H
#define FACEDETECT_MESSAGE_FACEPOSITION_H

#include <ros/service_traits.h>


#include <facedetect/FacePositionRequest.h>
#include <facedetect/FacePositionResponse.h>


namespace facedetect
{

struct FacePosition
{

typedef FacePositionRequest Request;
typedef FacePositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FacePosition
} // namespace facedetect


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::facedetect::FacePosition > {
  static const char* value()
  {
    return "d2c05ccb640a33497a3b05a5ba135029";
  }

  static const char* value(const ::facedetect::FacePosition&) { return value(); }
};

template<>
struct DataType< ::facedetect::FacePosition > {
  static const char* value()
  {
    return "facedetect/FacePosition";
  }

  static const char* value(const ::facedetect::FacePosition&) { return value(); }
};


// service_traits::MD5Sum< ::facedetect::FacePositionRequest> should match 
// service_traits::MD5Sum< ::facedetect::FacePosition > 
template<>
struct MD5Sum< ::facedetect::FacePositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::facedetect::FacePosition >::value();
  }
  static const char* value(const ::facedetect::FacePositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::facedetect::FacePositionRequest> should match 
// service_traits::DataType< ::facedetect::FacePosition > 
template<>
struct DataType< ::facedetect::FacePositionRequest>
{
  static const char* value()
  {
    return DataType< ::facedetect::FacePosition >::value();
  }
  static const char* value(const ::facedetect::FacePositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::facedetect::FacePositionResponse> should match 
// service_traits::MD5Sum< ::facedetect::FacePosition > 
template<>
struct MD5Sum< ::facedetect::FacePositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::facedetect::FacePosition >::value();
  }
  static const char* value(const ::facedetect::FacePositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::facedetect::FacePositionResponse> should match 
// service_traits::DataType< ::facedetect::FacePosition > 
template<>
struct DataType< ::facedetect::FacePositionResponse>
{
  static const char* value()
  {
    return DataType< ::facedetect::FacePosition >::value();
  }
  static const char* value(const ::facedetect::FacePositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FACEDETECT_MESSAGE_FACEPOSITION_H
