// Generated by gencpp from file speechrecog/Command.msg
// DO NOT EDIT!


#ifndef SPEECHRECOG_MESSAGE_COMMAND_H
#define SPEECHRECOG_MESSAGE_COMMAND_H

#include <ros/service_traits.h>


#include <speechrecog/CommandRequest.h>
#include <speechrecog/CommandResponse.h>


namespace speechrecog
{

struct Command
{

typedef CommandRequest Request;
typedef CommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Command
} // namespace speechrecog


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::speechrecog::Command > {
  static const char* value()
  {
    return "71ac060476c0905d0416477df3715d0f";
  }

  static const char* value(const ::speechrecog::Command&) { return value(); }
};

template<>
struct DataType< ::speechrecog::Command > {
  static const char* value()
  {
    return "speechrecog/Command";
  }

  static const char* value(const ::speechrecog::Command&) { return value(); }
};


// service_traits::MD5Sum< ::speechrecog::CommandRequest> should match 
// service_traits::MD5Sum< ::speechrecog::Command > 
template<>
struct MD5Sum< ::speechrecog::CommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::speechrecog::Command >::value();
  }
  static const char* value(const ::speechrecog::CommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::speechrecog::CommandRequest> should match 
// service_traits::DataType< ::speechrecog::Command > 
template<>
struct DataType< ::speechrecog::CommandRequest>
{
  static const char* value()
  {
    return DataType< ::speechrecog::Command >::value();
  }
  static const char* value(const ::speechrecog::CommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::speechrecog::CommandResponse> should match 
// service_traits::MD5Sum< ::speechrecog::Command > 
template<>
struct MD5Sum< ::speechrecog::CommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::speechrecog::Command >::value();
  }
  static const char* value(const ::speechrecog::CommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::speechrecog::CommandResponse> should match 
// service_traits::DataType< ::speechrecog::Command > 
template<>
struct DataType< ::speechrecog::CommandResponse>
{
  static const char* value()
  {
    return DataType< ::speechrecog::Command >::value();
  }
  static const char* value(const ::speechrecog::CommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPEECHRECOG_MESSAGE_COMMAND_H
