// Generated by gencpp from file speechrecog/CommandResponse.msg
// DO NOT EDIT!


#ifndef SPEECHRECOG_MESSAGE_COMMANDRESPONSE_H
#define SPEECHRECOG_MESSAGE_COMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speechrecog
{
template <class ContainerAllocator>
struct CommandResponse_
{
  typedef CommandResponse_<ContainerAllocator> Type;

  CommandResponse_()
    : command()  {
    }
  CommandResponse_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;




  typedef boost::shared_ptr< ::speechrecog::CommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speechrecog::CommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommandResponse_

typedef ::speechrecog::CommandResponse_<std::allocator<void> > CommandResponse;

typedef boost::shared_ptr< ::speechrecog::CommandResponse > CommandResponsePtr;
typedef boost::shared_ptr< ::speechrecog::CommandResponse const> CommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speechrecog::CommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speechrecog::CommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace speechrecog

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::speechrecog::CommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speechrecog::CommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speechrecog::CommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speechrecog::CommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speechrecog::CommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speechrecog::CommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speechrecog::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::speechrecog::CommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::speechrecog::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speechrecog/CommandResponse";
  }

  static const char* value(const ::speechrecog::CommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speechrecog::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n\
\n\
";
  }

  static const char* value(const ::speechrecog::CommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speechrecog::CommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speechrecog::CommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speechrecog::CommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEECHRECOG_MESSAGE_COMMANDRESPONSE_H
